[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Production context
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENV = "production" }

# Staging context
[context.staging]
  command = "npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENV = "staging" }

# Development context
[context.develop]
  command = "npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENV = "development" }

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "development", NEXT_PUBLIC_ENV = "development" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Add redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}